export const ActionType = {
  SEARCH_REPOSITORIES: 'SEARCH_REPOSITORIES',
  SEARCH_REPOSITORIES_SUCCESS: 'SEARCH_REPOSITORIES_SUCCESS',
  SEARCH_REPOSITORIES_ERROR: 'SEARCH_REPOSITORIES_ERROR',
  SEARCH_DELETE_REPOSITORY: 'SEARCH_DELETE_REPOSITORY'
};
